import React from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import Logo from '../Logo';

const CONTACT_EMAIL = 'wehearyou.studio@gmail.com';
const LAST_UPDATED = 'July 2026';

function Section({ title, children }) {
  return (
    <section className="mb-8">
      <h2 className="text-lg font-bold text-[#f0f0f0] mb-2">{title}</h2>
      <div className="text-sm text-[#aaaaaa] leading-relaxed space-y-2">{children}</div>
    </section>
  );
}

export default function Terms() {
  const navigate = useNavigate();
  return (
    <div className="min-h-screen bg-[#0a0a0a] text-[#f0f0f0]">
      <nav className="flex items-center justify-between px-6 py-4 border-b border-[#1a1a1a] max-w-4xl mx-auto">
        <button onClick={() => navigate('/')} className="flex items-center gap-2">
          <Logo size="md" />
        </button>
        <button
          onClick={() => navigate('/')}
          className="flex items-center gap-2 text-sm text-[#888888] hover:text-[#f0f0f0] transition-colors"
        >
          <ArrowLeft className="w-4 h-4" /> Back to home
        </button>
      </nav>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-[#666666] mb-10">Last updated: {LAST_UPDATED}</p>

        <Section title="1. Acceptance of Terms">
          <p>
            By accessing or using BeHeard ("the Service"), you agree to be bound by these Terms of
            Service. If you do not agree, do not use the Service.
          </p>
        </Section>

        <Section title="2. Description of Service">
          <p>
            BeHeard is an AI-powered marketing platform that helps you generate content and images,
            plan campaigns, write PR, and — where you connect a Meta account — schedule and publish
            posts to Facebook and Instagram, and view post analytics.
          </p>
        </Section>

        <Section title="3. Your Account">
          <p>
            You are responsible for maintaining the confidentiality of your account credentials and
            for all activity under your account. You must provide accurate information and are
            responsible for keeping it up to date.
          </p>
        </Section>

        <Section title="4. Acceptable Use">
          <p>You agree not to use BeHeard to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Create or publish content that is unlawful, hateful, deceptive, or infringing.</li>
            <li>Violate the terms or policies of connected platforms (including Meta/Facebook/Instagram).</li>
            <li>Attempt to disrupt, reverse-engineer, or gain unauthorized access to the Service.</li>
            <li>Send spam or content that violates others' rights.</li>
          </ul>
        </Section>

        <Section title="5. AI-Generated Content">
          <p>
            Content and images are generated by third-party AI models and may be inaccurate,
            incomplete, or unintended. You are responsible for reviewing, editing, and approving all
            content before publishing. You are solely responsible for what you publish through the
            Service.
          </p>
        </Section>

        <Section title="6. Third-Party Services">
          <p>
            The Service relies on third parties including Anthropic (Claude), Google (Gemini), and
            Meta. Your use of features involving these providers is also subject to their respective
            terms and policies. We are not responsible for third-party services or outages.
          </p>
        </Section>

        <Section title="7. Intellectual Property">
          <p>
            You retain ownership of the brand information and content you create. You grant us a
            limited license to process and store your content solely to provide the Service. The
            BeHeard platform, branding, and software remain our property.
          </p>
        </Section>

        <Section title="8. Termination">
          <p>
            You may stop using the Service and delete your account at any time. We may suspend or
            terminate access if you violate these Terms or use the Service in a way that could cause
            harm or legal liability.
          </p>
        </Section>

        <Section title="9. Disclaimers">
          <p>
            The Service is provided "as is" and "as available" without warranties of any kind, express
            or implied. We do not warrant that the Service will be uninterrupted, error-free, or that
            AI output will meet your requirements.
          </p>
        </Section>

        <Section title="10. Limitation of Liability">
          <p>
            To the maximum extent permitted by law, BeHeard shall not be liable for any indirect,
            incidental, or consequential damages, or for any loss of data, revenue, or profits arising
            from your use of the Service.
          </p>
        </Section>

        <Section title="11. Changes to These Terms">
          <p>
            We may update these Terms from time to time. Continued use of the Service after changes
            take effect constitutes acceptance of the revised Terms.
          </p>
        </Section>

        <Section title="12. Contact Us">
          <p>
            Questions about these Terms? Email us at{' '}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-[#BFFF00] hover:underline">{CONTACT_EMAIL}</a>.
          </p>
        </Section>
      </main>

      <footer className="px-6 py-6 border-t border-[#1a1a1a] text-center">
        <p className="text-xs text-[#555555]">© 2026 BeHeard · AI Marketing Platform</p>
      </footer>
    </div>
  );
}
